### ISSUE TITLE
how to listen on all interfaces ?

### ISSUE THREAD

**Issue by rafale0n** [Rices/Phishious#2]
Hello all,

Thanks for an amazing project. This is really useful for somebody who conducts Red Teaming exercises on behalf of our customers. I was wondering how can I make Phishious listen on all interfaces instead of just localhost ?

I am putting a small how-to and would not mind sharing your tips with others. 

Hope to hear from you soon.

**Comment by CanIPhish** [comment]
Hi,

There's a few ways to do this. The easiest, is to publish the project to your web hosting platform of choice (e.g. Azure/AWS). Personally I use Elastic Beanstalk for alot of my web-hosting and this project could be pretty seamlessly deployed via that avenue.
![image](https://user-images.githubusercontent.com/5109530/156964543-b9d89490-23ce-47c4-adc2-324a453fc40b.png)

Going down an alternate path, if you're just looking to host this on your local debugging machine, you can modify the IIS Express applicationhost.config file and remove the reference to localhost under the "bindingInformation" config which will then default to IIS Express debugging the app across all interfaces. This is outlined in more detail under this stackoverflow post - https://stackoverflow.com/questions/4866547/binding-iis-express-to-an-ip-address.

I hope this helps.

**Comment by CanIPhish** [comment]
Closing as answered
